/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JSpinner;

/**
 *
 * @author Kamil
 */
public class OrderConfirmation extends javax.swing.JPanel {

   
    private JFrame _frame;
    private ArrayList<Item> _cartContent;
    private Integer _spinnerValue;
    Map<Integer, Integer> _item = new HashMap<Integer, Integer>();
    private ArrayList<Address> _addressess = new ArrayList<Address>();
    
    /**
     * Creates new form OrderConfirmation
     */
    public OrderConfirmation(JFrame frame,ArrayList<Item> cartContent) {
        initComponents(); 
        _frame = frame;
        _cartContent = cartContent;
         initComboAndMap();
         initAddress();
         disabelSpinnerEdit();

         
    }
    
    private void disabelSpinnerEdit()
    {
        JFormattedTextField tf = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
        tf.setEditable(false); 
    }
    
    
     private void initAddress()
     {
        jComboAddress.setModel(new javax.swing.DefaultComboBoxModel<>());  
        
        
                Database db = Database.getDatabase();
        db.connect();
        String condition = "uzytkownik = " + db.getUserID();
        ArrayList<ArrayList<Object>> data2d = db.select2("id,ulica,miejscowosc,kod_pocztowy,nr_telefonu,nr_domu", "adres", condition,
                new ArrayList<SelectTypes>(Arrays.asList(
                        SelectTypes.INT,
                        SelectTypes.STRING,
                        SelectTypes.STRING,
                        SelectTypes.STRING,
                        SelectTypes.INT,
                        SelectTypes.INT)));

        for (ArrayList<Object> row : data2d) {
            _addressess.add(new Address(
                    (Integer) row.get(0),
                    (Integer) row.get(4),
                    (Integer) row.get(5),
                    (String) row.get(3),
                    (String) row.get(2),
                    (String) row.get(1)));

        }

        db.close();
        
        
         for (Address addr : _addressess) {    
              jComboAddress.addItem(addr.getMiejscowosc());
         }

        
     }

    private void initComboAndMap()
    {
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());
        for(Item item : _cartContent)
        {
            _item.put(item.getId_towaru(),1);
            jComboBox1.addItem(item.getNazwa());  
             
        }

    }
    
    private void changeItemNumber(Integer sign)
    {
        if (sign>0) {
        //add
        
        
        }else
        {//sub
            
            
        }
    }
    
    
    private boolean checkForAddItemNumber()
    {
       boolean status =false; //false jesli nie wolno dodac wiecej sztuk produktu
       Integer liczbaDostepnychSztuk = 0;
       
       
       //wersja ze sprawdzeniem bazy danych
//       Database db = Database.getDatabase();
//       db.connect();      
//
//        String  selectedItem = _cartContent.get(jComboBox1.getSelectedIndex()).getNazwa();
//        String condition = "nazwa = '"+selectedItem+"'";
//        ArrayList<Object> data = db.select("liczba_sztuk","towar",condition,SelectTypes.INT);     
//        for (Object result : data) {
//            liczbaDostepnychSztuk = (Integer)result;
//        }
//        db.close();
        


        
        liczbaDostepnychSztuk = _cartContent.get(jComboBox1.getSelectedIndex()).getLiczba_sztuk();
          
        
        if (liczbaDostepnychSztuk +1 == (Integer)jSpinner1.getValue()) {
            status =false;
        }else
        {
            status = true;
        }
 
        
        return status;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jComboPayment = new javax.swing.JComboBox<>();
        jComboAddress = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelZipCode = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboPayment2 = new javax.swing.JComboBox<>();
        jLabelNrDomu = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel1.setText(" zamówienia");

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 36)); // NOI18N
        jLabel2.setText("Potwierdzenie");

        jButton1.setText("Potwierdź");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Zrezygnuj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Sposób płatności:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Przedmiot:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Ilość:");

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jSpinner1MouseExited(evt);
            }
        });
        jSpinner1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jSpinner1InputMethodTextChanged(evt);
            }
        });
        jSpinner1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinner1PropertyChange(evt);
            }
        });

        jComboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Przy odbiorze", "Przelew", "PayPal" }));
        jComboPayment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboPaymentItemStateChanged(evt);
            }
        });
        jComboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPaymentActionPerformed(evt);
            }
        });

        jComboAddress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAddressActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Adres:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Twoje dane:");

        jLabelCity.setText("City");

        jLabelAddress.setText("Address");

        jLabelZipCode.setText("ZipCode");

        jLabelPhone.setText("Phone");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Sposób transportu:");

        jComboPayment2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kurier", "Poczta", "Odbiór osobisty" }));
        jComboPayment2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboPayment2ItemStateChanged(evt);
            }
        });
        jComboPayment2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPayment2ActionPerformed(evt);
            }
        });

        jLabelNrDomu.setText("nr domu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCity)
                                        .addComponent(jLabelAddress)
                                        .addComponent(jLabelZipCode)
                                        .addComponent(jLabelPhone)
                                        .addComponent(jLabelNrDomu)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboPayment2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel2)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboPayment2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelZipCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPhone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNrDomu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(368, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    _frame.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

         Integer id_towaru =_cartContent.get(jComboBox1.getSelectedIndex()).getId_towaru();
         jSpinner1.setValue(_item.get(id_towaru));
         
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        //performer dziala lepiej
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        
        //System.out.println("zmiana stanu");
        
        if ((Integer)jSpinner1.getValue() < 1) {
            jSpinner1.setValue(1);
            _spinnerValue = (Integer)jSpinner1.getValue();
        }else
        {
            
            if (checkForAddItemNumber()) {
                _item.put(_cartContent.get(jComboBox1.getSelectedIndex()).getId_towaru(),(Integer)jSpinner1.getValue());
                _spinnerValue = (Integer)jSpinner1.getValue();
            }else
            {
                jSpinner1.setValue(_spinnerValue);
            }
            
            
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1MouseExited

    private void jComboPaymentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboPaymentItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPaymentItemStateChanged

    private void jComboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPaymentActionPerformed

    private void jComboPayment2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboPayment2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPayment2ItemStateChanged

    private void jComboPayment2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPayment2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPayment2ActionPerformed

    private void jSpinner1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinner1PropertyChange
        // TODO add your handling code here:
        System.out.println("property changed");
    }//GEN-LAST:event_jSpinner1PropertyChange

    private void jSpinner1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jSpinner1InputMethodTextChanged
        // TODO add your handling code here:
        System.out.println("method changed");
    }//GEN-LAST:event_jSpinner1InputMethodTextChanged

    private void jComboAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAddressActionPerformed
        // TODO add your handling code here:
        
        Integer nr_domu = _addressess.get(jComboAddress.getSelectedIndex()).getNr_domu();
        String miejscowosc = _addressess.get(jComboAddress.getSelectedIndex()).getMiejscowosc();
        String adres = _addressess.get(jComboAddress.getSelectedIndex()).getUlica();
        String kod_pocztowy = _addressess.get(jComboAddress.getSelectedIndex()).getKod_pocztowy();
        Integer nr_telefonu = _addressess.get(jComboAddress.getSelectedIndex()).getNr_telefonu();
        
        //System.out.println(nr_domu);
        
        jLabelAddress.setText(adres+" (ulica)");
        jLabelCity.setText(miejscowosc+" (miejscowość)");
        jLabelPhone.setText(nr_telefonu.toString()+" (telefon)");
        jLabelZipCode.setText(kod_pocztowy+" (kod pocztowy)");
        jLabelNrDomu.setText(nr_domu.toString()+" (nr domu)");
        
        //addr.getMiejscowosc()
        
    }//GEN-LAST:event_jComboAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboAddress;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboPayment;
    private javax.swing.JComboBox<String> jComboPayment2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelNrDomu;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelZipCode;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
